// Generated by Wrangler by running `wrangler types`

interface Env {
	BOT_INFO: "{\n\"id\":7997754709,\n\"is_bot\":true,\n\"first_name\":\"IELTS{AI}Hub\",\n\"username\":\"ielts_aihub_bot\",\n\"can_join_groups\":true,\n\"can_read_all_group_messages\":false,\n\"supports_inline_queries\":false,\n\"can_connect_to_business\":false,\n\"has_main_web_app\":false\n}";
}
